export const APP_NAME = 'FoodAxis'

export const ORDER_STATUS_LABELS = {
  received: 'Received',
  preparing: 'Preparing',
  ready: 'Ready',
  out_for_delivery: 'Out for Delivery',
  delivered: 'Delivered',
  cancelled: 'Cancelled',
}

export const ORDER_STATUS_COLORS = {
  received: 'bg-blue-100 text-blue-700',
  preparing: 'bg-amber-100 text-amber-700',
  ready: 'bg-emerald-100 text-emerald-700',
  out_for_delivery: 'bg-violet-100 text-violet-700',
  delivered: 'bg-gray-100 text-gray-700',
  cancelled: 'bg-red-100 text-red-700',
}

export const PAYMENT_METHODS = [
  { id: 'card', label: 'Credit/Debit Card', icon: 'CreditCard' },
  { id: 'cash', label: 'Cash on Delivery', icon: 'Banknote' },
  { id: 'wallet', label: 'Digital Wallet', icon: 'Wallet' },
]

export const DEMO_MENU_ITEMS = [
  {
    id: 1,
    name: 'Classic Chicken Burger',
    description: 'Juicy grilled chicken with fresh lettuce, tomato, and special sauce',
    price: 450,
    category: 'Burgers',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400',
    prepTime: '15 min',
    rating: 4.5,
    calories: 520,
    isAvailable: true,
  },
  {
    id: 2,
    name: 'Margherita Pizza',
    description: 'Fresh mozzarella, tomato sauce, and basil on thin crust',
    price: 680,
    category: 'Pizza',
    image: 'https://images.unsplash.com/photo-1604382354936-07c5d9983bd3?w=400',
    prepTime: '20 min',
    rating: 4.7,
    calories: 800,
    isAvailable: true,
  },
  {
    id: 3,
    name: 'Grilled Salmon',
    description: 'Atlantic salmon with lemon butter sauce and seasonal vegetables',
    price: 950,
    category: 'Main Course',
    image: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=400',
    prepTime: '25 min',
    rating: 4.8,
    calories: 450,
    isAvailable: true,
  },
  {
    id: 4,
    name: 'Caesar Salad',
    description: 'Crisp romaine lettuce with parmesan, croutons, and Caesar dressing',
    price: 320,
    category: 'Starters',
    image: 'https://images.unsplash.com/photo-1550304943-4f24f54ddde9?w=400',
    prepTime: '10 min',
    rating: 4.3,
    calories: 280,
    isAvailable: true,
  },
  {
    id: 5,
    name: 'Chocolate Lava Cake',
    description: 'Warm chocolate cake with molten center and vanilla ice cream',
    price: 380,
    category: 'Desserts',
    image: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=400',
    prepTime: '12 min',
    rating: 4.9,
    calories: 420,
    isAvailable: true,
  },
  {
    id: 6,
    name: 'Mango Smoothie',
    description: 'Fresh mango blended with yogurt and honey',
    price: 220,
    category: 'Beverages',
    image: 'https://images.unsplash.com/photo-1623065422902-30a2d299bbe4?w=400',
    prepTime: '5 min',
    rating: 4.6,
    calories: 180,
    isAvailable: true,
  },
]

export const DEMO_ORDERS = [
  {
    id: 'ORD-001',
    customer: 'John Doe',
    items: [{ name: 'Classic Chicken Burger', qty: 2 }, { name: 'Mango Smoothie', qty: 1 }],
    total: 1120,
    status: 'preparing',
    type: 'delivery',
    address: '123 Main St, Dhaka',
    time: '2026-08-10 12:30',
    rider: null,
  },
  {
    id: 'ORD-002',
    customer: 'Sarah Smith',
    items: [{ name: 'Margherita Pizza', qty: 1 }],
    total: 680,
    status: 'received',
    type: 'dine-in',
    table: 'T-05',
    time: '2026-08-10 12:45',
  },
  {
    id: 'ORD-003',
    customer: 'Mike Johnson',
    items: [{ name: 'Grilled Salmon', qty: 1 }, { name: 'Caesar Salad', qty: 1 }],
    total: 1270,
    status: 'out_for_delivery',
    type: 'delivery',
    address: '456 Park Ave, Dhaka',
    time: '2026-08-10 12:15',
    rider: 'Alex Rider',
  },
]